name: PUBLISH FRONTEND BUILD
on:
  push:
    branches:
      - main
jobs:
  buildAndPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        run: docker login ${{ secrets.CI_REGISTRY_URL }} -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Tag
        run: |
          docker build -t ${{ secrets.CONTAINER_NAME }} -f Dockerfile .
          docker tag ${{ secrets.CONTAINER_NAME }} ${{ secrets.CI_REGISTRY_URL }}/${{ secrets.NAMESPACE }}/${{ secrets.CONTAINER_NAME }}:latest

      - name: Push
        run: docker push ${{ secrets.CI_REGISTRY_URL }}/${{ secrets.NAMESPACE }}/${{ secrets.CONTAINER_NAME }}:latest
